print("Welcome to the Band Name Generator! ")
a= str(input("what was the city you grew up in? \n"))
b= str(input("What was the name of your first pet? \n"))
c= a.capitalize()+ " "+ b.capitalize()
print("Your band's name should be: ", c)